# Generated by Django 3.2.9 on 2021-11-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapiAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Persons',
        ),
    ]
