# Generated by Django 3.2.9 on 2021-11-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapiAPP', '0002_rename_user_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
